#!/usr/bin/env bash

# Initializae our user-defined list of packages to install
package_list=("kakoune" "tmux")

# Loop through our package_list to install each one
for package in ${package_list[@]}; do
  # For each loop, we error handle by checking if the package already exists
  # using the -Q (Query) and -s (search) option,
  # we use > /dev/null to discard the output since we are only concerned
  # if the package exists (exit code 0)
  if pacman -Qs $package > /dev/null; then
    echo "Package: $package is already installed."
    # We install the package if it does not exist (exit code 1), 
    # we use the --noconfirm option since we are running pacman in script and want to skip confirmation messages
  else
    echo "Installing $package ..."
    pacman -Syu --noconfirm $package
  fi
done
